### ISSUE TITLE
Messages with multiple instances not loaded/parsed/visualized correctly

### ISSUE THREAD

**Issue by maxpolzin** [foxglove/ulog#2]
**Description**

The "actuator_outputs" messages do not get read/visualized properly. In Foxglove Studio, when opening and reading a .ulog file, the topics panel shows one message: actuator_outputs. When visualizing one of the elements of the array actuator_outputs, e.g. actuator_outputs[4], an oscillation between two values can be observed.   

Visualization of actuator_outputs[4] in Foxglove Studio:
![image](https://github.com/foxglove/ulog/assets/20051567/6644c1f1-31e3-49d5-aeff-6ead042507c5)

To verify this is not a problem of the .ulog file, we can load and visualize the same ulog-file in PlotJuggler. Here we can see two messages:  actuator_outputs.00 and actuator_outputs.01. When visualizing for example the 4th value of these two messages, we observe them displayed correctly. 

Visualization of actuator_outputs.00[4] (red) and actuator_outputs.01[4] (blue) in PlotJuggler:
![image](https://github.com/foxglove/ulog/assets/20051567/7cd868a1-6fd1-4983-a8a0-34fbb9ece8e1)

I assume this is a problem with the ulog-parser? Do you have any hints, how I can try to fix the parsing/visualization?

- Version: Foxglove Studio 2.8.0
- Platform: Ubuntu 22.04

**Steps To Reproduce**

Take a ulog-file, e.g. this one [log_2_2024-7-3-17-44-26_nothing.zip](https://github.com/user-attachments/files/16094918/log_2_2024-7-3-17-44-26_nothing.zip), and plot actuator_outputs.output[4].

**Expected Behavior**

The proper visualization would be two lines showing actuator_outputs.00[4] and actuator_outputs.01[4] as two lines. One line around 1500 and the other one around 0.

**Comment by achim-k** [comment]
Thanks for reporting this bug and apologies for the delayed response, this fell off the radar.

The reason for this bug is that the `multi_id` field from the [Subscription Message](https://docs.px4.io/main/en/dev_log/ulog_file_format.html#a-subscription-message) is currently not taken into account. https://github.com/foxglove/ulog/pull/4 makes changes to the API to expose this field. We will fix this also on Foxglove side to take the `multiId` field into account when generating the topic names.

**Comment by achim-k** [comment]
Internal tracking issue: [FG-9293](https://linear.app/foxglove/issue/FG-9293)
